# Backend 1 Dockerfile
FROM python:3.11

# Set the working directory
WORKDIR /app

# Copy the rest of the application code
COPY . .

# Install the dependencies
RUN pip install -r requirements.txt

EXPOSE 5001


# Command to run the application
CMD ["python", "data_processing.py"]