name: Deploy to Koyeb
on:
  push:
    branches: [deploy]
  workflow_dispatch:
env:
  LOWER_OWNER: mohammedbilal-0001
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Koyeb CLI
        uses: koyeb-community/koyeb-actions@v2
        with:
          api_token: ${{ secrets.KOYEB_TOKEN }}
      
      - name: Create Registry Secret in Koyeb
        run: |
          koyeb secret create github-registry \
            --type registry-private 
            --docker-hub-username ${{ github.actor }} \
            ---docker-hub-password ${{ secrets.GITHUB_TOKEN }} \
            --docker-hub-server ghcr.io
      
      - name: Deploy Frontend to Koyeb
        run: |
          koyeb service create frontend-service \
            --docker ghcr.io/${{ env.LOWER_OWNER }}/frontend:latest \
            --ports 3000:http \
            --routes "/frontend:3000" \
            --regions fra \
            --env "NODE_ENV=production" \
            --env "REACT_APP_BACKEND1_URL=/backend1" \
            --env "REACT_APP_BACKEND2_URL=/backend2" \
            --min-scale 0 \
            --max-scale 1 \
            --docker-private-registry-secret github-registry
      
      - name: Deploy Backend1 to Koyeb
        run: |
          koyeb service create backend1-service \
            --docker ghcr.io/${{ env.LOWER_OWNER }}/backend1:latest \
            --ports 5001:http \
            --routes "/backend1:5001" \
            --regions fra \
            --env "FLASK_ENV=production" \
            --min-scale 0 \
            --max-scale 1 \
            --docker-private-registry-secret github-registry
      
      - name: Deploy Backend2 to Koyeb
        run: |
          koyeb service create backend2-service \
            --docker ghcr.io/${{ env.LOWER_OWNER }}/backend2:latest \
            --ports 5002:http \
            --routes "/backend2:5002" \
            --regions fra \
            --env "FLASK_ENV=production" \
            --min-scale 0 \
            --max-scale 1 \
            --docker-private-registry-secret github-registry
