name: Deploy to Koyeb

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: "acebm"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Koyeb CLI
        uses: koyeb-community/koyeb-actions@v2
        with:
          api_token: ${{ secrets.KOYEB_TOKEN }}

      - name: Deploy to Koyeb
        env:
          KOYEB_TOKEN: ${{ secrets.KOYEB_TOKEN }}  # GitHub Secret
        run: |
          koyeb  --token $KOYEB_TOKEN service create aide-project \
            --docker ${{ env.DOCKERHUB_USERNAME }}/backend1:latest \
            --docker ${{ env.DOCKERHUB_USERNAME }}/frontend:latest \
            --docker ${{ env.DOCKERHUB_USERNAME }}/backend2:latest \
            --ports "3000:http,5001:http,5002:http" \
            --routes "/frontend:3000,/backend1:5001,/backend2:5002" \
            --regions fra \
            --env "NODE_ENV=production" \
            --env "FLASK_ENV=production" \
            --env "REACT_APP_BACKEND1_URL=/backend1" \
            --env "REACT_APP_BACKEND2_URL=/backend2" \
            --min-scale 0 \
            --max-scale 1
