name: Deploy to Koyeb

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: "acebm"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Frontend (Docker CLI)
        run: |
          
          docker run --rm \
            koyeb/koyeb-cli service create churn-detection/aide-project-b-f \
             --docker acebm/backend:latest \
             --docker acebm/frontend:latest \
             --docker acebm/backend2:latest \
             --ports "3000:http,5001:http,5002:http" \
             --routes "/frontend:3000,/backend1:5001,/backend2:5002" \
             --regions fra \
             --env "NODE_ENV=production" \
             --env "FLASK_ENV=production" \
             --env "REACT_APP_BACKEND1_URL=/backend1" \
             --env "REACT_APP_BACKEND2_URL=/backend2" \
             --min-scale 0 \
             --max-scale 1 \
             --token "${{ secrets.KOYEB_API_TOKEN }}"
