name: Deploy to Koyeb
on:
  push:
    branches: [deploy]
  workflow_dispatch:
env:
  LOWER_OWNER: mohammedbilal-0001
  GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ env.GHCR_TOKEN }}
      
      - name: Install Koyeb CLI
        uses: koyeb-community/koyeb-actions@v2
        with:
          api_token: ${{ secrets.KOYEB_TOKEN }}
      
      - name: Verify Images Accessibility
        run: |
          echo "Verifying frontend image..."
          docker pull ghcr.io/${{ env.LOWER_OWNER }}/frontend:latest
          echo "Verifying backend1 image..."
          docker pull ghcr.io/${{ env.LOWER_OWNER }}/backend1:latest
          echo "Verifying backend2 image..."
          docker pull ghcr.io/${{ env.LOWER_OWNER }}/backend2:latest
          echo "All images exist and are accessible"
      
      - name: Deploy Frontend to Koyeb with Debug Mode
        run: |
          koyeb --debug service create frontend-service \
            --docker ghcr.io/${{ env.LOWER_OWNER }}/frontend:latest \
            --ports 3000:http \
            --routes "/frontend:3000" \
            --regions fra \
            --env "NODE_ENV=production" \
            --env "REACT_APP_BACKEND1_URL=/backend1" \
            --env "REACT_APP_BACKEND2_URL=/backend2" \
            --min-scale 0 \
            --max-scale 1
      
      - name: Deploy Backend1 to Koyeb with Debug Mode
        run: |
          koyeb --debug service create backend1-service \
            --docker ghcr.io/${{ env.LOWER_OWNER }}/backend1:latest \
            --ports 5001:http \
            --routes "/backend1:5001" \
            --regions fra \
            --env "FLASK_ENV=production" \
            --min-scale 0 \
            --max-scale 1
      
      - name: Deploy Backend2 to Koyeb with Debug Mode
        run: |
          koyeb --debug service create backend2-service \
            --docker ghcr.io/${{ env.LOWER_OWNER }}/backend2:latest \
            --ports 5002:http \
            --routes "/backend2:5002" \
            --regions fra \
            --env "FLASK_ENV=production" \
            --min-scale 0 \
            --max-scale 1
