name: Build and Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Backend 1
        uses: docker/build-push-action@v5
        with:
          context: ./Backend_1
          file: ./Backend_1/Dockerfile.backend1
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/backend1:latest
            ghcr.io/${{ github.repository_owner }}/backend1:${{ github.sha }}

      - name: Build and push Backend 2
        uses: docker/build-push-action@v5
        with:
          context: ./Backend_2
          file: ./Backend_2/Dockerfile.backend2
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/backend2:latest
            ghcr.io/${{ github.repository_owner }}/backend2:${{ github.sha }}

      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile.frontend
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/frontend:latest
            ghcr.io/${{ github.repository_owner }}/frontend:${{ github.sha }}

  deploy-to-koyeb:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Koyeb
        uses: koyeb/action@v1
        with:
          koyeb_token: ${{ secrets.KOYEB_TOKEN }}
          service_name: aide-project
          docker: |
            ghcr.io/${{ github.repository_owner }}/backend1:latest
            ghcr.io/${{ github.repository_owner }}/backend2:latest
            ghcr.io/${{ github.repository_owner }}/frontend:latest
          app_name: aide-project
          ####################################
          # Koyeb-specific configuration
          ####################################
          ####################################
          # Koyeb-specific configuration
          ####################################
          ports: "3000:http,5001:http,5002:http"
          regions: "fra"
          ####################################
          # Environment variables
          ####################################
          env: |
            NODE_ENV=production
            FLASK_ENV=production
            REACT_APP_BACKEND1_URL=https://backend1
            REACT_APP_BACKEND2_URL=https://backend2