name: Build and Push Images to Docker Hub

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: "acebm"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Backend 1
        uses: docker/build-push-action@v5
        with:
          context: ./Backend_1
          file: ./Backend_1/Dockerfile.backend1
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/backend1:latest
            ${{ env.DOCKERHUB_USERNAME }}/backend1:${{ github.sha }}

      - name: Build and push Backend 2
        uses: docker/build-push-action@v5
        with:
          context: ./Backend_2
          file: ./Backend_2/Dockerfile.backend2
          push: true
          secrets: |
            DAGSHUB_TOKEN=${{ secrets.DAGSHUB_TOKEN }}
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/backend2:latest
            ${{ env.DOCKERHUB_USERNAME }}/backend2:${{ github.sha }}

      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile.frontend
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/frontend:latest
            ${{ env.DOCKERHUB_USERNAME }}/frontend:${{ github.sha }}

      - name: Create deployment trigger
        run: echo "${{ github.sha }}" > .deployment_trigger
